export const TOTEMS = [
  { key: "bird", label: "Птица" },
  { key: "bear", label: "Медведь" },
  { key: "bug", label: "Жук" },
  { key: "butterfly", label: "Бабочка" },
  { key: "camel", label: "Верблюд" },
  { key: "cat", label: "Кот" },
  { key: "crab", label: "Краб" },
  { key: "dinosaur", label: "Динозавр" },
  { key: "duck", label: "Утка" },
  { key: "fish", label: "Рыба" },
  { key: "flea", label: "Блоха" },
  { key: "fox", label: "Лисица" },
  { key: "frog", label: "Лягушка" },
  { key: "kangaroo", label: "Кенгуру" },
  { key: "koala", label: "Коала" },
  { key: "dog", label: "Собака" },
  { key: "moose", label: "Лось" },
  { key: "panda", label: "Панда" },
  { key: "pelican", label: "Пеликан" },
  { key: "penguin", label: "Пингвин" },
  { key: "snake", label: "Змея" },
  { key: "turtle", label: "Черепаха" },
  { key: "walrus", label: "Морж" },
  { key: "wombat", label: "Вомбат" },
];